travis:
  secure:
    BINSTAR_TOKEN: CeYetlXvEPUT+YuzRZsXRnwQ35YhcS8rVHMyWoxm7xf7u0hZ7hqt+XKrDo/6RFZ9GZLUcOM6GFo54j23YlESxkPiCJ/dpIdIR6KrdWDFRXZrUa9S7fhrkNzWhemW7o+l7+GFEZARzccJcl454E8HInrjoSGGG0uYQdaTCv7XuN5rPbJqo2aR0u+5Llc2tSJy+pu7pY0JqZEbkQ7381czTYlCVpXJ6XsCOCCGkVU0zLDi1P0pjt9uqT7W0qzAhedYj0yNIEQpfk5r1Co5TmyVklA4YGmTURoRZxYQ2cv/Rq7Q6ooZ5DIHRuibn0GcT/AvRVnnMBqtBt0z2kvUlH6EaFVic75zkchb2wdah6n46ozkkl4jZF/Y2Mqz1V2d3PdFDTnbp71OfdZIa+9nxuHSCtjvwpt0K0XY6YMXNDpw61g1zzczghB1XhOuvwq19MxVKbi/mmF4czPzjTzVklX15DiXVwQEHOohcdzFoK3uo33h81AU3CvkBXgT5R/uxAeJ69WDmSRYHvUyL1pkwtW7ErYkpqKG98tKMoWb3PT6aUeLj5cvCwXI+OO/qazuy9hUU3/aoirybuoldV1VyQpbsXMNXJE73EwC8lTN1ReIHC75UgF5XGhTaSExH/L8N8Abx5qqCk98CBubLvvfjEeMNKGXrmXTHErrA/Oum+elSt4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
