travis:
  secure:
    BINSTAR_TOKEN: LHOcowO/iI94HJixHmIED8L/4s4LLTFNOV41Xcvv6ywiR+dafFBkVqXR20YmYeXkNdbL2sOoFwIPTZBe7G4+Yjy4zLfM39PMYkUPIQj9iVAsnYStoxLbT6IjhrKANozyOMnut6h1Uc6S13EqCalP9qs4XO1onugKrsHb/qnpIEurLAti0cB1d8jjgH+oDxOB5srDl42+AFnyj/XpvM0IY5lyOGKmQSJz6KjABsSmWdmMDRok3kZ+SdHqeUKZU+PuPPwwgdzLhnKGIZy+JvmOkAEiwU5AJsmsEInBjTz3GPeJZPhZRHVcCx1fT4Cs834yjLfy3Ea+klMQcnFiuuKfl6sPDl9NeIynttuDbBQAJDmc6Jn3gt7s8G6yGCd6Dpp2JG60qBduJ7GAyRhelWcAb+10QGdsRSddaTJi+vjAbbpLtoszTY6Zf608wWoZe7pOJQbwkEle0H8OjH4PKZLHxswjyBvhOwoAzQtPubgh1DmbFELmXBnCBqsAdser6zwe6+ZA7lyuUS7mLCIobjyWocCzLD6wEq1SBoJfxicQ+WRo+VfQTBBeFShU6aq4yDIfsj3uUx4l8A3ckI+fZh8nGb3EtKzF13Opn0i8V834HWouAmwzkOs84UyCIsKRyv1ErWPSJrf5L3BmV3hDnkAKno2Fmcbceys85ulJtjmPs+k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
